#configs/baseline_hyp.yaml
# Focal Loss 用于类别不均衡
fl_gamma: 1.5   # 适度提升对小类的关注

# --- Data augmentation ---
hsv_v: 0.2               # 亮度增强
degrees: 5.0
scale: 0.1
sheer: 0.0
translate: 0.0
perspective: 0.0

flipud: 0.5           # 50% 概率上下翻转
fliplr: 0.0           # 禁用左右翻转

mosaic: 0.0
mixup: 0.10           # 混合增强（模拟白斑噪声）
copy_paste: 0.15      # 模拟随机亮块伪影
erasing: 0.1          # 20% 概率随机擦除小块(伪影效果)
