#configs/dataset.yaml
path: ../crop_datasets    # 根目录（包含 images/ 和 labels/）
train: images/train
val: images/val
test: images/test

nc: 7

names:
  0: BI-RADS-0
  1: BI-RADS-1
  2: BI-RADS-2
  3: BI-RADS-3
  4: BI-RADS-4
  5: BI-RADS-5
  6: BI-RADS-6
